namespace VRC_cantalkcn.Services;

public static class UiLocalizationService
{
    private static readonly Dictionary<string, Dictionary<string, string>> Translations = new(StringComparer.OrdinalIgnoreCase)
    {
        ["en"] = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["主页"] = "Home",
            ["设置"] = "Settings",
            ["语音引擎"] = "Voice Engine",
            ["插件"] = "Plugins",
            ["翻译设置"] = "Translation",
            ["语音识别"] = "Speech Input",
            ["音频播放器"] = "Audio Player",
            ["输入内容"] = "Input",
            ["输入要说的话"] = "Enter text to speak",
            ["发送并朗读"] = "Send & Speak",
            ["点击说话 (单击)"] = "Tap to Talk (Single Click)",
            ["语音识别输出: -"] = "Speech Output: -",
            ["微调"] = "Tuning",
            ["语速"] = "Rate",
            ["语调"] = "Pitch",
            ["音量"] = "Volume",
            ["GPT语速"] = "GPT Speed",
            ["强制音画同步"] = "Force A/V Sync",
            ["GPT 去标点"] = "GPT Remove Punctuation",
            ["语音识别后自动发送"] = "Auto Send After Recognition",
            ["手机控制端 (扫码连接)"] = "Mobile Controller (QR)",
            ["手机和电脑需连同一个 WiFi"] = "Phone and PC must be on the same Wi-Fi",
            ["音频路由 (双声卡输出)"] = "Audio Routing (Dual Output)",
            ["监听设备 (给自己听)"] = "Monitor Device (Local)",
            ["VRC设备 (给麦克风/VBCable)"] = "VRC Device (Mic/VBCable)",
            ["刷新"] = "Refresh",
            ["界面语言"] = "UI Language",
            ["本机局域网IP"] = "Local IP",
            ["全局唤醒热键 (示例: f9 或 ctrl+q)"] = "Global Hotkey (e.g. f9 or ctrl+q)",
            ["代理地址"] = "Proxy",
            ["GPT-SoVITS 自动启动 (api.bat)"] = "GPT-SoVITS Auto Start (api.bat)",
            ["选择"] = "Browse",
            ["保存配置"] = "Save Settings",
            ["角色档案"] = "Voice Profile",
            ["新建"] = "New",
            ["删除"] = "Delete",
            ["保存档案并切模型"] = "Save Profile & Switch Model",
            ["TTS 引擎"] = "TTS Engine",
            ["输入语言"] = "Input Language",
            ["Edge 发音人"] = "Edge Voice",
            ["API 地址"] = "API URL",
            ["GPT 模型路径 (*.ckpt)"] = "GPT Model Path (*.ckpt)",
            ["SoVITS 模型路径 (*.pth)"] = "SoVITS Model Path (*.pth)",
            ["音频语音 (参考音频路径)"] = "Reference Audio Path",
            ["音频文字"] = "Prompt Text",
            ["音频语言"] = "Prompt Language",
            ["Fish API Key"] = "Fish API Key",
            ["Fish 引用 ID"] = "Fish Reference ID",
            ["插件目录"] = "Plugin Folder",
            ["重载插件"] = "Reload Plugins",
            ["启用翻译"] = "Enable Translation",
            ["辅助显示语言（最多勾选 3 个）"] = "Display Languages (max 3)",
            ["中文"] = "Chinese",
            ["英语"] = "English",
            ["日语"] = "Japanese",
            ["韩语"] = "Korean",
            ["俄语"] = "Russian",
            ["法语"] = "French",
            ["德语"] = "German",
            ["西语"] = "Spanish",
            ["泰语"] = "Thai",
            ["越语"] = "Vietnamese",
            ["印尼语"] = "Indonesian",
            ["阿语"] = "Arabic",
            ["强制输出（自动发音）"] = "Forced Output (Auto Voice)",
            ["翻译引擎"] = "Translation Engine",
            ["TTS 强制语言"] = "Forced TTS Language",
            ["不指定（默认读原文）"] = "None (Read Original)",
            ["AI 预设（兼容 OpenAI 格式）"] = "AI Presets (OpenAI Compatible)",
            ["智谱(免费)"] = "Zhipu (Free)",
            ["硅基(Qwen)"] = "SiliconFlow (Qwen)",
            ["Universal API"] = "Universal API",
            ["Universal API Key"] = "Universal API Key",
            ["Universal Model"] = "Universal Model",
            ["Universal Prompt"] = "Universal Prompt",
            ["DeepL Key"] = "DeepL Key",
            ["保存翻译设置并生效"] = "Save Translation Settings",
            ["语音识别引擎"] = "Speech Engine",
            ["麦克风设备"] = "Microphone Device",
            ["跟随系统默认"] = "Use System Default",
            ["选择模型目录"] = "Select Model Folder",
            ["Vosk 模型路径"] = "Vosk Model Path",
            ["识别后自动发送"] = "Auto Send After Recognition",
            ["并行模式：TTS 播放时继续采集"] = "Parallel Mode: Keep Capturing During TTS Playback",
            ["开：边播边采（响应更快，可能串音）；关：稳定模式（播放 TTS 时暂停采集）。"] = "On: speak while TTS plays (faster, may cause crosstalk). Off: stable mode (pause capture during TTS playback).",
            ["音频文件"] = "Audio File",
            ["打开文件"] = "Open File",
            ["播放 / 暂停"] = "Play / Pause",
            ["停止"] = "Stop",
            ["就绪"] = "Ready",
            ["开始语音输入"] = "Start Speech Input",
            ["停止语音输入"] = "Stop Speech Input",
            ["暂停"] = "Pause",
            ["翻译中..."] = "Translating...",
            ["语音合成中..."] = "Synthesizing...",
            ["播放中..."] = "Playing...",
            ["语音输入中..."] = "Listening...",
            ["语音输入已停止"] = "Speech input stopped",
            ["配置已保存"] = "Settings saved",
            ["翻译设置已保存并生效"] = "Translation settings saved",
            ["辅助显示语言最多选择 3 个。"] = "You can select up to 3 display languages.",
            ["已应用预设: {0}"] = "Preset applied: {0}",
            ["至少保留一个角色档案。"] = "At least one profile must remain.",
            ["档案已保存。"] = "Profile saved.",
            ["插件重载: 当前版本待实现动态插件执行。"] = "Plugin reload: dynamic plugin execution is not implemented yet.",
            ["GPT-SoVITS 模型已切换。"] = "GPT-SoVITS model switched.",
            ["错误: {0}"] = "Error: {0}",
            ["语音输入错误: {0}"] = "Speech input error: {0}",
            ["热键注册失败: {0}"] = "Hotkey registration failed: {0}",
            ["打开插件目录失败: {0}"] = "Failed to open plugin folder: {0}",
            ["模型切换失败: {0}"] = "Model switch failed: {0}",
            ["界面语言已切换"] = "UI language switched",
            ["语音识别热键 (示例: f5)"] = "Speech Hotkey (e.g. f5)",
            ["发送热键 (示例: f6)"] = "Send Hotkey (e.g. f6)",
            ["全局唤醒热键"] = "Global Hotkey",
            ["语音识别热键"] = "Speech Hotkey",
            ["发送热键"] = "Send Hotkey",
            ["English"] = "English",
            ["日本語"] = "Japanese",
            ["한국어"] = "Korean"
        },
        ["ja"] = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["主页"] = "ホーム",
            ["设置"] = "設定",
            ["语音引擎"] = "音声エンジン",
            ["插件"] = "プラグイン",
            ["翻译设置"] = "翻訳設定",
            ["语音识别"] = "音声認識",
            ["音频播放器"] = "オーディオプレーヤー",
            ["输入内容"] = "入力内容",
            ["输入要说的话"] = "話すテキストを入力",
            ["发送并朗读"] = "送信して読み上げ",
            ["点击说话 (单击)"] = "クリックして話す（単押し）",
            ["语音识别输出: -"] = "認識結果: -",
            ["微调"] = "微調整",
            ["语速"] = "話速",
            ["语调"] = "ピッチ",
            ["音量"] = "音量",
            ["GPT语速"] = "GPT話速",
            ["强制音画同步"] = "音声と表示を強制同期",
            ["GPT 去标点"] = "GPT 句読点除去",
            ["语音识别后自动发送"] = "認識後に自動送信",
            ["手机控制端 (扫码连接)"] = "モバイル操作（QR接続）",
            ["手机和电脑需连同一个 WiFi"] = "スマホとPCを同じWi-Fiに接続",
            ["音频路由 (双声卡输出)"] = "オーディオルーティング（二重出力）",
            ["监听设备 (给自己听)"] = "モニターデバイス（自分用）",
            ["VRC设备 (给麦克风/VBCable)"] = "VRCデバイス（マイク/VBCable）",
            ["刷新"] = "更新",
            ["界面语言"] = "表示言語",
            ["本机局域网IP"] = "ローカルIP",
            ["全局唤醒热键 (示例: f9 或 ctrl+q)"] = "グローバルホットキー（例: f9 / ctrl+q）",
            ["代理地址"] = "プロキシ",
            ["GPT-SoVITS 自动启动 (api.bat)"] = "GPT-SoVITS 自動起動 (api.bat)",
            ["选择"] = "選択",
            ["保存配置"] = "設定を保存",
            ["角色档案"] = "音声プロファイル",
            ["新建"] = "新規",
            ["删除"] = "削除",
            ["保存档案并切模型"] = "保存してモデル切替",
            ["TTS 引擎"] = "TTSエンジン",
            ["输入语言"] = "入力言語",
            ["Edge 发音人"] = "Edge 音声",
            ["API 地址"] = "API URL",
            ["GPT 模型路径 (*.ckpt)"] = "GPTモデルパス (*.ckpt)",
            ["SoVITS 模型路径 (*.pth)"] = "SoVITSモデルパス (*.pth)",
            ["音频语音 (参考音频路径)"] = "参照音声パス",
            ["音频文字"] = "プロンプトテキスト",
            ["音频语言"] = "プロンプト言語",
            ["Fish 引用 ID"] = "Fish 参照ID",
            ["插件目录"] = "プラグインフォルダ",
            ["重载插件"] = "プラグイン再読み込み",
            ["启用翻译"] = "翻訳を有効化",
            ["辅助显示语言（最多勾选 3 个）"] = "表示補助言語（最大3つ）",
            ["中文"] = "中国語",
            ["英语"] = "英語",
            ["日语"] = "日本語",
            ["韩语"] = "韓国語",
            ["俄语"] = "ロシア語",
            ["法语"] = "フランス語",
            ["德语"] = "ドイツ語",
            ["西语"] = "スペイン語",
            ["泰语"] = "タイ語",
            ["越语"] = "ベトナム語",
            ["印尼语"] = "インドネシア語",
            ["阿语"] = "アラビア語",
            ["强制输出（自动发音）"] = "強制出力（自動音声）",
            ["翻译引擎"] = "翻訳エンジン",
            ["TTS 强制语言"] = "TTS強制言語",
            ["不指定（默认读原文）"] = "指定なし（原文読み上げ）",
            ["AI 预设（兼容 OpenAI 格式）"] = "AIプリセット（OpenAI互換）",
            ["智谱(免费)"] = "Zhipu（無料）",
            ["硅基(Qwen)"] = "SiliconFlow（Qwen）",
            ["保存翻译设置并生效"] = "翻訳設定を保存して適用",
            ["语音识别引擎"] = "音声認識エンジン",
            ["麦克风设备"] = "マイクデバイス",
            ["跟随系统默认"] = "システム既定を使用",
            ["选择模型目录"] = "モデルフォルダを選択",
            ["Vosk 模型路径"] = "Voskモデルパス",
            ["识别后自动发送"] = "認識後に自動送信",
            ["并行模式：TTS 播放时继续采集"] = "並行モード: TTS再生中も音声入力を継続",
            ["开：边播边采（响应更快，可能串音）；关：稳定模式（播放 TTS 时暂停采集）。"] = "オン: 再生しながら入力（応答は速いが音の回り込みあり）。オフ: 安定モード（TTS再生中は入力を一時停止）。",
            ["音频文件"] = "音声ファイル",
            ["打开文件"] = "ファイルを開く",
            ["播放 / 暂停"] = "再生 / 一時停止",
            ["停止"] = "停止",
            ["就绪"] = "準備完了",
            ["开始语音输入"] = "音声入力を開始",
            ["停止语音输入"] = "音声入力を停止",
            ["暂停"] = "一時停止",
            ["翻译中..."] = "翻訳中...",
            ["语音合成中..."] = "音声合成中...",
            ["播放中..."] = "再生中...",
            ["语音输入中..."] = "音声入力中...",
            ["语音输入已停止"] = "音声入力を停止しました",
            ["配置已保存"] = "設定を保存しました",
            ["翻译设置已保存并生效"] = "翻訳設定を保存しました",
            ["辅助显示语言最多选择 3 个。"] = "表示補助言語は3つまで選択できます。",
            ["已应用预设: {0}"] = "プリセットを適用しました: {0}",
            ["至少保留一个角色档案。"] = "少なくとも1つのプロファイルを残す必要があります。",
            ["档案已保存。"] = "プロファイルを保存しました。",
            ["插件重载: 当前版本待实现动态插件执行。"] = "プラグイン再読み込み: 動的実行は未実装です。",
            ["GPT-SoVITS 模型已切换。"] = "GPT-SoVITSモデルを切り替えました。",
            ["错误: {0}"] = "エラー: {0}",
            ["语音输入错误: {0}"] = "音声入力エラー: {0}",
            ["热键注册失败: {0}"] = "ホットキー登録失敗: {0}",
            ["打开插件目录失败: {0}"] = "プラグインフォルダを開けませんでした: {0}",
            ["模型切换失败: {0}"] = "モデル切替失敗: {0}",
            ["界面语言已切换"] = "表示言語を切り替えました",
            ["语音识别热键 (示例: f5)"] = "音声認識ホットキー (例: f5)",
            ["发送热键 (示例: f6)"] = "送信ホットキー (例: f6)",
            ["全局唤醒热键"] = "グローバルホットキー",
            ["语音识别热键"] = "音声認識ホットキー",
            ["发送热键"] = "送信ホットキー",
            ["English"] = "英語",
            ["한국어"] = "韓国語"
        },
        ["ko"] = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["主页"] = "홈",
            ["设置"] = "설정",
            ["语音引擎"] = "음성 엔진",
            ["插件"] = "플러그인",
            ["翻译设置"] = "번역 설정",
            ["语音识别"] = "음성 인식",
            ["音频播放器"] = "오디오 플레이어",
            ["输入内容"] = "입력 내용",
            ["输入要说的话"] = "말할 텍스트 입력",
            ["发送并朗读"] = "전송 및 읽기",
            ["点击说话 (单击)"] = "클릭해서 말하기(단일 클릭)",
            ["语音识别输出: -"] = "인식 출력: -",
            ["微调"] = "미세 조정",
            ["语速"] = "속도",
            ["语调"] = "피치",
            ["音量"] = "볼륨",
            ["GPT语速"] = "GPT 속도",
            ["强制音画同步"] = "오디오/화면 강제 동기화",
            ["GPT 去标点"] = "GPT 문장부호 제거",
            ["语音识别后自动发送"] = "인식 후 자동 전송",
            ["手机控制端 (扫码连接)"] = "모바일 컨트롤러(QR 연결)",
            ["手机和电脑需连同一个 WiFi"] = "휴대폰과 PC를 같은 Wi-Fi에 연결",
            ["音频路由 (双声卡输出)"] = "오디오 라우팅(듀얼 출력)",
            ["监听设备 (给自己听)"] = "모니터 장치(자기 청취)",
            ["VRC设备 (给麦克风/VBCable)"] = "VRC 장치(마이크/VBCable)",
            ["刷新"] = "새로고침",
            ["界面语言"] = "표시 언어",
            ["本机局域网IP"] = "로컬 IP",
            ["全局唤醒热键 (示例: f9 或 ctrl+q)"] = "전역 단축키(예: f9 또는 ctrl+q)",
            ["代理地址"] = "프록시",
            ["GPT-SoVITS 自动启动 (api.bat)"] = "GPT-SoVITS 자동 시작(api.bat)",
            ["选择"] = "선택",
            ["保存配置"] = "설정 저장",
            ["角色档案"] = "음성 프로필",
            ["新建"] = "새로 만들기",
            ["删除"] = "삭제",
            ["保存档案并切模型"] = "프로필 저장 및 모델 전환",
            ["TTS 引擎"] = "TTS 엔진",
            ["输入语言"] = "입력 언어",
            ["Edge 发音人"] = "Edge 음성",
            ["API 地址"] = "API 주소",
            ["GPT 模型路径 (*.ckpt)"] = "GPT 모델 경로 (*.ckpt)",
            ["SoVITS 模型路径 (*.pth)"] = "SoVITS 모델 경로 (*.pth)",
            ["音频语音 (参考音频路径)"] = "참조 오디오 경로",
            ["音频文字"] = "프롬프트 텍스트",
            ["音频语言"] = "프롬프트 언어",
            ["Fish 引用 ID"] = "Fish 참조 ID",
            ["插件目录"] = "플러그인 폴더",
            ["重载插件"] = "플러그인 다시 불러오기",
            ["启用翻译"] = "번역 사용",
            ["辅助显示语言（最多勾选 3 个）"] = "보조 표시 언어(최대 3개)",
            ["中文"] = "중국어",
            ["英语"] = "영어",
            ["日语"] = "일본어",
            ["韩语"] = "한국어",
            ["俄语"] = "러시아어",
            ["法语"] = "프랑스어",
            ["德语"] = "독일어",
            ["西语"] = "스페인어",
            ["泰语"] = "태국어",
            ["越语"] = "베트남어",
            ["印尼语"] = "인도네시아어",
            ["阿语"] = "아랍어",
            ["强制输出（自动发音）"] = "강제 출력(자동 음성)",
            ["翻译引擎"] = "번역 엔진",
            ["TTS 强制语言"] = "TTS 강제 언어",
            ["不指定（默认读原文）"] = "지정 안 함(원문 읽기)",
            ["AI 预设（兼容 OpenAI 格式）"] = "AI 프리셋(OpenAI 호환)",
            ["智谱(免费)"] = "Zhipu(무료)",
            ["硅基(Qwen)"] = "SiliconFlow(Qwen)",
            ["保存翻译设置并生效"] = "번역 설정 저장 및 적용",
            ["语音识别引擎"] = "음성 인식 엔진",
            ["麦克风设备"] = "마이크 장치",
            ["跟随系统默认"] = "시스템 기본값 사용",
            ["选择模型目录"] = "모델 폴더 선택",
            ["Vosk 模型路径"] = "Vosk 모델 경로",
            ["识别后自动发送"] = "인식 후 자동 전송",
            ["并行模式：TTS 播放时继续采集"] = "병렬 모드: TTS 재생 중에도 음성 수집 계속",
            ["开：边播边采（响应更快，可能串音）；关：稳定模式（播放 TTS 时暂停采集）。"] = "켜기: 재생 중 동시 수집(응답 빠름, 혼입 가능). 끄기: 안정 모드(TTS 재생 중 수집 일시정지).",
            ["音频文件"] = "오디오 파일",
            ["打开文件"] = "파일 열기",
            ["播放 / 暂停"] = "재생 / 일시정지",
            ["停止"] = "정지",
            ["就绪"] = "준비됨",
            ["开始语音输入"] = "음성 입력 시작",
            ["停止语音输入"] = "음성 입력 중지",
            ["暂停"] = "일시정지",
            ["翻译中..."] = "번역 중...",
            ["语音合成中..."] = "음성 합성 중...",
            ["播放中..."] = "재생 중...",
            ["语音输入中..."] = "음성 입력 중...",
            ["语音输入已停止"] = "음성 입력이 중지됨",
            ["配置已保存"] = "설정이 저장됨",
            ["翻译设置已保存并生效"] = "번역 설정이 저장됨",
            ["辅助显示语言最多选择 3 个。"] = "보조 표시 언어는 최대 3개까지 선택할 수 있습니다.",
            ["已应用预设: {0}"] = "프리셋 적용됨: {0}",
            ["至少保留一个角色档案。"] = "최소 1개의 프로필은 유지해야 합니다.",
            ["档案已保存。"] = "프로필이 저장되었습니다.",
            ["插件重载: 当前版本待实现动态插件执行。"] = "플러그인 다시 불러오기: 동적 실행은 아직 미구현입니다.",
            ["GPT-SoVITS 模型已切换。"] = "GPT-SoVITS 모델 전환 완료.",
            ["错误: {0}"] = "오류: {0}",
            ["语音输入错误: {0}"] = "음성 입력 오류: {0}",
            ["热键注册失败: {0}"] = "단축키 등록 실패: {0}",
            ["打开插件目录失败: {0}"] = "플러그인 폴더 열기 실패: {0}",
            ["模型切换失败: {0}"] = "모델 전환 실패: {0}",
            ["界面语言已切换"] = "표시 언어가 변경되었습니다",
            ["语音识别热键 (示例: f5)"] = "음성 인식 핫키 (예: f5)",
            ["发送热键 (示例: f6)"] = "전송 핫키 (예: f6)",
            ["全局唤醒热键"] = "전역 핫키",
            ["语音识别热键"] = "음성 인식 핫키",
            ["发送热键"] = "전송 핫키",
            ["English"] = "영어",
            ["日本語"] = "일본어"
        }
    };

    public static string NormalizeLanguage(string? code)
    {
        if (string.IsNullOrWhiteSpace(code))
        {
            return "zh";
        }

        var c = code.Trim().ToLowerInvariant();
        return c switch
        {
            "en" => "en",
            "ja" => "ja",
            "ko" => "ko",
            _ => "zh"
        };
    }

    public static string Translate(string? languageCode, string sourceText)
    {
        var lang = NormalizeLanguage(languageCode);
        if (lang == "zh" || string.IsNullOrEmpty(sourceText))
        {
            return sourceText;
        }

        if (Translations.TryGetValue(lang, out var dict) && dict.TryGetValue(sourceText, out var translated))
        {
            return translated;
        }

        return sourceText;
    }
}
